package com.vitalong.bluetest2.greendaodb;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.vitalong.bluetest2.bean.RealDataCached;

import com.vitalong.bluetest2.greendaodb.RealDataCachedDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig realDataCachedDaoConfig;

    private final RealDataCachedDao realDataCachedDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        realDataCachedDaoConfig = daoConfigMap.get(RealDataCachedDao.class).clone();
        realDataCachedDaoConfig.initIdentityScope(type);

        realDataCachedDao = new RealDataCachedDao(realDataCachedDaoConfig, this);

        registerDao(RealDataCached.class, realDataCachedDao);
    }
    
    public void clear() {
        realDataCachedDaoConfig.clearIdentityScope();
    }

    public RealDataCachedDao getRealDataCachedDao() {
        return realDataCachedDao;
    }

}
